### ISSUE TITLE
a 12 block ascension bypass (on aristois 1.14.4 client)

### ISSUE THREAD

**Issue by ghost** [Olexorus/WitherAC#3]
Describe the bug
a 12 block ascension bypass (on aristois 1.14.4 client)

Version Information

WitherAC Anticheat Version (Latest is not a version): 0.14.0
ProtocolLib Version (Latest is not a version): 4.4.0
Bukkit/Spigot Version (Latest is not a version): CraftBukkit version git-Spigot-1981d55-c88867e (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Are you using the ViaVersion plugin?: No

Server Logs (Pastebin link)
Watch The Video

Screenshots/Video
https://streamable.com/9p11e

Other Information
heres the download to the client https://aristois.net/zips/1.14.4-Aristois-Latest.zip
and you can use the format for reporting issues or bugs if you want i dont mind

**Comment by Olexorus** [comment]
That's weird, thanks for the report

**Comment by Olexorus** [comment]
I just released 0.14.1 which should nerf this and make it not useful anymore.

Please reopen if it's still an issue.
