### ISSUE TITLE
Angle / Reach False Flag

### ISSUE THREAD

**Issue by WaifuBeforeLaifu** [Olexorus/WitherAC#37]
Having thorns on your armor causes false positives on the angle/killaura and reach/killaura checks. Usually happens when attacked by skeletons. WAC v0.16.2 minecraft 1.15.2 Papermc v77

Yes this does happen on a vanilla client, I just happened to record it while using fabric https://streamable.com/sp9zt

**Comment by Olexorus** [comment]
Thanks for the report, fixed in 0.17.0
