### ISSUE TITLE
Stuck when walking on top of wall

### ISSUE THREAD

**Issue by maximeurban** [Olexorus/WitherAC#49]
The issue I'm having is when I'm walking on top of a cobblestone wall, for example, I get stuck and I can't get out by another way than flying. I also get a false Packet Spoof alert.

**Comment by beanbot25** [comment]
I also have this problem. I have the anticheat blocking off, so it doesnt kickback a players movement. https://youtu.be/w3nROS7WNtE but you get kicked for "hacks"

**Comment by lerokko** [comment]
Can confirm this is happening to me as well, with paper-134 and WAC 0.21.2.

**Comment by Olexorus** [comment]
Fixed in 0.22.0
