### ISSUE TITLE
WitherAC doesn't block BlockFly (Scaffold)

### ISSUE THREAD

**Issue by 12emin34** [Olexorus/WitherAC#51]
Server version: This server is running Tuinity version git-Tuinity-d3dc35c (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
WitherAC version: 0.21.2
Client: Sigma 5.0.0b10 (Jello)
I have tried every BlockFly mode and WitherAC just doesn't detect it

**Comment by Olexorus** [comment]
Tower/AutoBridge hacks are currently not detected, which is why they're not listed on the plugin page. They're planned at some point but atm there is higher priority stuff.
